"""update users table

Revision ID: 7882f8fb7f2a
Revises: 3e9e0970e13e
Create Date: 2026-01-22 20:47:08.342531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7882f8fb7f2a'
down_revision: Union[str, Sequence[str], None] = '3e9e0970e13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('f_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('l_name', sa.String(length=255), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'l_name')
    op.drop_column('users', 'f_name')
    # ### end Alembic commands ###
