"""rmove complete column

Revision ID: 95f17cbff358
Revises: f2c16ebb2bc4
Create Date: 2026-01-13 18:04:27.382687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f17cbff358'
down_revision: Union[str, Sequence[str], None] = 'f2c16ebb2bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('description', sa.String(length=50), nullable=True))
    op.drop_column('todos', 'description1')
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('todos', sa.Column('description1', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('todos', 'description')
    # ### end Alembic commands ###
