"""rename description column

Revision ID: f2c16ebb2bc4
Revises: e7b92096ffaf
Create Date: 2026-01-13 17:54:08.245947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c16ebb2bc4'
down_revision: Union[str, Sequence[str], None] = 'e7b92096ffaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('description1', sa.String(length=50), nullable=True))
    op.drop_column('todos', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('todos', 'description1')
    # ### end Alembic commands ###
